name: Create docker container on release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v tests.py
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Create Docker container
      run: |
        # Step 1: Authenticate
        docker login docker.pkg.github.com -u dubass83 -p ${{ secrets.GITHUB_TOKEN }}
        # Step 2: Build and Tag
        docker build -t docker.pkg.github.com/dubass83/slack2telegram/app1:${{steps.vars.outputs.tag}} .
    - name: Publish Docker container
      run: |
        # Step 3: Publish
        docker push docker.pkg.github.com/dubass83/slack2telegram/app1:${{steps.vars.outputs.tag}}

